### ISSUE TITLE
Add ability to preconfigure a hyperty

### ISSUE THREAD

**Issue by Endebert** [reTHINK-project/dev-hyperty-toolkit#12]
Currently, while there is a configuration object provided in the constructor of a hyperty, there is no way to add entries to that object outside of that hyperty besides manually adding entries in the configuration property of the generated hyperty descriptor in /resources/descriptors/Hyperties.json.

My suggestion is to have a configuration.json file or something like that in `/src/<myhyperty>/`, that would be taken into consideration when generating the hyperty descriptor.

**Comment by pchainho** [comment]
This is a great idea. We would go even further: to have a "descriptor.json" in the  `src/<hyperty>` where we would include configurable descriptor parameters including the "configuration", "hypertyType", "dataObjects" etc.

**Comment by vitormsilva** [comment]
I added to the branch develop on dev-hyperty repository, only for some hyperties, the initial configuration file.

The name isn't `descriptor.json` but `<name-of-hyperty>.hy.json`, because we need to identify the Hyperty, and the folder name could not represent the name of it.

You could try, if all works well, with the [develop-improves branch](https://github.com/reTHINK-project/dev-hyperty-toolkit/tree/develop-improves)

Look at this issue #15
