### ISSUE TITLE
Hello World

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-hyperty-toolkit#2]
from #1 @sbecot proposes / comments:
>> the example -and reporter hyperty + observer hyperty is not useful at this stage (and by the way the pattern is not described before -please don't describe it-).

Not sure what you mean here. This is the way Hyperties work. The report - observer pattern is described in more detail in the tutorials but the idea is just to have a quick starting guide without giving much details.

> add a picture to figure out what is deployed where: we can't figure out why to use pt platform to deploy an example on a local machine. 

ok, perhaps have this picture [here](https://github.com/reTHINK-project/dev-hyperty-toolkit/blob/master/README.md#cloud-and-local-development-environment)?

This was the testbed that was available at the time we wrote the readme. I understand Quobis is proposing to provide a dedicated dev testbed: @antonroman ?

> And I don't understand the localhost config (127.0.0.1 hybroker.rethink.ptinovacao.pt). If we need to install a messaging node first, let's do it, I think it may be more clear. It could be easily done thought a docker container.

We set as default the usage of a Cloud Environment as the one that is simpler and faster to start with ie you don't have to install any back end server locally. The changes in the hosts file is to reach the localhost where you have the Local Catalogue, when making requests to the dev catalogue towards the localhost. I'll try to explain this better.

We are currently missing a manual to guide the setup a local development environment. I don't think we have this, yet.

> The examples should be provided directly in ES5 to avoid a step.

Developers have selected ES6 as a more powerful programming language. Since the conversion is done "under the scene", there is no additional step to be performed by the developer.

> Before step 2 the command npm start should be run, but it is not specified.

Not sure if I got this one but `npm start` is after `npm install`
By the way we have to update this to put as parameter the environment (production or development)

> set the cloud development environment domain at system.config.json is not very clear, the example specify production and development, but not cloud.

This is just to set the domains to be used for the two different environments, not whether it is cloud or local.

**Comment by sbecot** [comment]
I'll try to do my best to answer.

> This is the way Hyperties work. The report - observer pattern    

I understand, but observer is just a pattern. I'd like to focus on the function before the means. The first example should display something, that's all. Here you are focusing on "How it is done". To make it work the first time I don't care of the guts.

> perhaps have this picture here?   

I would rather put it just after Quick guide  to setup the scene.

> Not sure if I got this one but npm start is after npm install

Right, but, my feeling is that the 'npm start' comes very late in the process. As the code is already provided, I think a short explanation to launch it would be nice, and then we detail the content.

Concerning the Cloud, I think it is not the right term to use. What you mean is just remote, but is there a difference? The environment has to be present somewhere and we need to put this address. The address can be local or remote, it works exactly the same. More than this, even if you deploy it locally you need to enter the URL or IP of the runtime, otherwise you can only use a local browser to test. In this case what is the difference between local or cloud? I think distinguishing local and cloud is not necessary, and I think the term "Cloud" may be confusing (too wide).

**Comment by pchainho** [comment]
I think the readme has been already updated with this feedback. We'll reopen if needed
