### ISSUE TITLE
Speedup Toolkit Installation

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-hyperty-toolkit#22]
The Toolkit installation takes too long and is a big obstacle for the adoption by the web community. This was one of the main inputs from TADHack

Depending on the computing power and internet access it can take 30 min or more.

Thus, we would like to discuss how to speedup the toolkit installation.

I this point I see two types of approaches:

1- use an alternative to npm like:
- https://github.com/yarnpkg/yarn
- https://github.com/alexanderGugel/ied,
- https://www.npmjs.com/package/npmd,

2- build a docker image with all dependencies and publish to docker hub. In the last release, we already provide a docker image, but without having all dependencies. Here we also noticed problems with the image docker installation.

other alternatives to speedup the toolkit installation? opinions? comments?

**Comment by sbecot** [comment]
What are the steps that took long time? Software download? Configuration? Understanding?

Replacing a tool by another (less known) may not be simpler.
If you provide a docker image, you need to install docker first. I'm not sure this will be simpler for the developers.

A proposal: we should avoid to modify the "host" file on the developer computer, with access to local fake pt urls. This is a bit confusing. "localhost" or 127.0.0.1 should be the rule for the developer. If not, we can provide an online development testbeds with a shared catalogue. This means that we must provide a configuration with specific urls (I think an issue has been provided), which could accept paths like http://127.0.0.1/catalogue http://127.0.0.1/registry instead of http://catalogue.xxxx.pt/

**Comment by pchainho** [comment]
it is really just `npm install` that takes a long time.

At this point we already provide the 2 options, npm and docker, If developers already have docker installed they may prefer to use docker. 

regarding the change of the hosts file, I agree we should avoid this. We are working on that and hopefully next release we won't need to change it anymore :)

**Comment by sbecot** [comment]
Then we can also: 
- have less dependencies
- download dependencies once and provide them in the package so the npm install is not necessary.

**Comment by pchainho** [comment]
I was told we have already reduced as much as possible all our dependencies. But in case anyone thinks we can still remove more dependencies pls let us know.

> download dependencies once and provide them in the package so the npm install is not necessary.

If I understood correctly, that's the 2nd approach ie to build a docker image with all dependencies included.

**Comment by sbecot** [comment]
Not necessarily. If you want to develop on windows that wouldn't be so good.
Why a dev-toolkit folder with all dependencies included wouldn't be enough?

**Comment by jmcrom** [comment]
I guess most dependencies are located within the _node_modules_ folder so just including this in the toolkit itself would be enough

**Comment by pchainho** [comment]
Committing the node_modules to git could be a good option but has some disadvantages namely size in git and I also understand they are compiled for a certain OS.

I've found this [article](https://medium.com/search?q=my-node-modules-are-in-git-again) with a [solution](https://github.com/bestander/npm-git-lock) that seems to address these weak points. What do you think?

**Comment by pchainho** [comment]
@vitormsilva managed to greatly speedup the toolkit installation. Pls have a try with branch "toolkit-node".

**Comment by pchainho** [comment]
It has been released
